# Generated by Django 4.2.1 on 2023-05-24 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='image_ids',
        ),
        migrations.AddField(
            model_name='room',
            name='image_ids',
            field=models.ManyToManyField(null=True, to='webapp.images'),
        ),
    ]
